bump to fix vsce
     > ts-node ./scripts/build/package.ts
    ERROR  Invalid extension version '1.50.0-090797363055'
    Error: Command failed: vsce package